config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  #resources :discharges 
  get 'discharges/:id/show', to: 'discharges#show', as: 'discharge'
  post 'record/:id/discharge/new', to:'discharges#create', as: 'new_record_discharge'
  get 'record/:id/discharge/new', to: 'discharges#new'
  
  resources :doctor
  resources :records
  post 'doctor/:id/records/new', to: 'records#create', as: 'new_doctor_record'
  get 'doctor/:id/records/new', to: 'records#new'
  get 'doctor/:id/records/index', to: 'records#index',
        as: 'doctor_records'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root 'main#home'
  get 'user/profile', as: 'user_root'
  get 'doctor/profile', as: 'doctor_root'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discharge.rb
class Discharge < ApplicationRecord
end

app/controllers/discharges_controller.rb
class DischargesController < InheritedResources::Base

  def index
    @discharges = Discharge.all
  end

  # GET /discharges/1 or /records/1.json
  def show
    unless Discharge.where(record_id: params[:id]).exists?
        #render template: 'discharges/_notexists'
        flash.notice = 'Извините но доктор еще не дал свою рекомендацию'
        redirect_back  fallback_location: { action: "profile"}
      else
        @discharge = Discharge.where(record_id: params[:id]).first
      end
  end

  # GET /discharges/new
  def new
    @discharge = Discharge.new
  end

  # GET /discharges/1/edit
  def edit
  end

  # POST /discharges or /records.json
  def create
    @discharge = Discharge.new(discharge_params)
    @discharge.record_id = params[:id]
    @record = Record.find(@discharge.record_id)
    @record.isOpen = false
    @record.save

    respond_to do |format|
      if @discharge.save
        format.html { redirect_to root_path, notice: "Discharge was successfully created." }
        redirect_to current_doctor
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discharge.errors, status: :unprocessable_entity }
      end
    else
	format.html{ redirect_to doctor_index_path, notice: "Sorry to many discharges"}
    end
  end

  # PATCH/PUT /discharges/1 or /records/1.json
  def update
    respond_to do |format|
      if @discharge.update(record_params)
        format.html { redirect_to @discharge, notice: "Discharge was successfully updated." }
        format.json { render :show, status: :ok, location: @discharge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discharge.errors, status: :unprocessable_entity }
      end
    end
  end
  private

    def discharge_params
      params.permit(:body)
    end

end

app/helpers/discharges_helper.rb
module DischargesHelper
end

app/views/discharges/_form.html.erb
<div class="card">

<div class="card-body text-centre">
<%= form_with model: @discharges do |form| %>
  <% if discharge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discharge.errors.count, "error") %> prohibited this discharge from being saved:</h2>

      <ul>
        <% discharge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

   <div>
     <%= form.text_area :body,
       {class: 'form-control',
       placeholder: 'Рекомендация'}%>
  </div>

  <div class="input-group btn">
    <%= form.submit 'Соxранить',
      class: 'btn btn-primary', label: 'commit'%>
  </div>
<% end %>

</div>
</div>

app/views/discharges/edit.html.erb
<h1>Editing Discharge</h1>

<%= render 'form', discharge: @discharge %>

<%= link_to 'Show', @discharge %> |
<%= link_to 'Back', discharges_path %>

app/views/discharges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discharges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discharges.each do |discharge| %>
      <tr>
        <td><%= discharge.body %></td>
        <td><%= discharge.record_id %></td>
        <td><%= link_to 'Show', discharge %></td>
        <td><%= link_to 'Edit', edit_discharge_path(discharge) %></td>
        <td><%= button_to 'Destroy', discharge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discharge', new_discharge_path %>

app/views/discharges/new.html.erb
<div class="card-header">
  Новая рекомендация
</div>
<div class="card">
  <%= render 'form', discharge: @discharge %>
</div>

app/views/discharges/show.html.erb
<div class="card">
  <div class="card-header">
  Рекомендация
  </div>
  <div class="card-body">
    <%= @discharge.body %>
  </div>
</div>