config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  #resources :discharges 
  get 'discharges/:id/show', to: 'discharges#show', as: 'discharge'
  post 'record/:id/discharge/new', to:'discharges#create', as: 'new_record_discharge'
  get 'record/:id/discharge/new', to: 'discharges#new'
  
  resources :doctor
  resources :records
  post 'doctor/:id/records/new', to: 'records#create', as: 'new_doctor_record'
  get 'doctor/:id/records/new', to: 'records#new'
  get 'doctor/:id/records/index', to: 'records#index',
        as: 'doctor_records'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root 'main#home'
  get 'user/profile', as: 'user_root'
  get 'doctor/profile', as: 'doctor_root'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:phone]
    validates :name, :surname, presence: true
    validates :surname, uniqueness: true

    has_many :records
    has_many :users, through: :records

  def email_required?
    false
  end

  def email_changed?
    false
  end

  # use this instead of email_changed? for rails >= 5.1
  def will_save_change_to_email?
    false
  end

end

app/controllers/doctor_controller.rb
class DoctorController < ApplicationController
    
    def index
      if doctor_signed_in?
        @doctors = Doctor.where.
            not(id: current_doctor.id)
      else
    	  @doctors = Doctor.all
      end
    end

    def show
      @doctor = current_doctor
    end
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/views/doctors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/doctors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Войти", new_session_path(resource_name),
    {class: 'alert-link'}%><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Зарегистрироваться", 
    new_registration_path(resource_name),
    {class: 'alert-link'}%><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Забыли пароль?", new_password_path(resource_name),
    {class: 'alert-link'}%><br />
<% end %>