config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  #resources :discharges 
  get 'discharges/:id/show', to: 'discharges#show', as: 'discharge'
  post 'record/:id/discharge/new', to:'discharges#create', as: 'new_record_discharge'
  get 'record/:id/discharge/new', to: 'discharges#new'
  
  resources :doctor
  resources :records
  post 'doctor/:id/records/new', to: 'records#create', as: 'new_doctor_record'
  get 'doctor/:id/records/new', to: 'records#new'
  get 'doctor/:id/records/index', to: 'records#index',
        as: 'doctor_records'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root 'main#home'
  get 'user/profile', as: 'user_root'
  get 'doctor/profile', as: 'doctor_root'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_one :discharge
end

app/controllers/records_controller.rb
class RecordsController < InheritedResources::Base
  before_action :set_record, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:create]

  # GET /records or /records.json
  def index
    @records = Record.all.where(doctor_id: params[:id])
  end

  # GET /records/1 or /records/1.json
  def show
      @record = Record.find(params[:id])
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  def doctor
    @doctor = Doctor.find(@record.id)
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)
    @record.user = current_user
    @record.doctor_id = params[:id]
    @record.isOpen = true

    @count = Record.where(doctor_id: params[:id]).count
    respond_to do |format|
    @count += 1
    if @count <= 10
      if @record.save
        format.html { redirect_to user_root_path, notice: "Запись успешно создана."}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    else
	format.html{ redirect_to doctor_index_path, notice: "Извините но у врача максимально допустимое количество записей"}
    end
  end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
        params.
	   permit(:title, :description, :record_at)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<div class="container card text-center">
<div class="row">
  <div class="col card-header text-left">Новая запись</div>
<%= form_with model: @records do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col">
    <%= form.text_field :title, {class: 'form-control', placeholder: 'Название'} %>
  </div>

  <div class="col">
    <%= form.text_area :description, {class: 'form-control', placeholder: 'Описание'} %>
  </div>

  <div class="col">
    <%= form.label 'Время записи:'%>

    <%= form.datetime_local_field :record_at,
      {class: 'btn btn-info btn-sm'}%>
  </div>

  <div class="col">
    <%= form.submit 'Соxранить',
      class: 'btn btn-primary' %>
  </div>
<% end %>
</div>
</div>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice alert-warning"><%= notice %></p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Название</th>
      <th>Время</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @current_doctor.records.each do |record| %>
      <tr>
        <td><%= record.title %></td>
        <td>
          <%= record.record_at.day %>/<%= record.record_at.month %>
          <%= record.record_at.hour %>:<%= record.record_at.min %>
        </td>
        <td><%= link_to 'Детальнее', record %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/records/new.html.erb
<%= render 'form', record: @record %>

app/views/records/show.html.erb
<div class="card">
  <div class="card-header">
    <span class="card-text">
      Запись от
      <%= @record.user.name %>
      <%= @record.user.surname %>
    </span>
    <div class="card-subtitle text-muted">
      <% if @record.isOpen? %>

      <div class="card-text text-success">
        Открыта
      </div>
    <% else %>
      <div class="card-text text-danger">
        Закрыта
      </div>
    <% end %>
    </div>
  </div>
    <div class="card-body">
      <div class="card-tezt">
        <%= @record.title %>
      </div>
      <div class="card-tezt">
        <%= @record.description %>
      </div>
      <% if @record.isOpen == false %>
      <div class="card-tezt" >
        <%= link_to 'Дать рекомендации', new_record_discharge_path(@record),{class: 'btn btn-primary disabled'} %></div>
    <% else %>
  <div class="card-tezt" >
        <%= link_to 'Дать рекомендации', new_record_discharge_path(@record),{class: 'btn btn-primary '} %></div>
    <% end %>
    </div>
</div>
</div>