config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  #resources :discharges 
  get 'discharges/:id/show', to: 'discharges#show', as: 'discharge'
  post 'record/:id/discharge/new', to:'discharges#create', as: 'new_record_discharge'
  get 'record/:id/discharge/new', to: 'discharges#new'
  
  resources :doctor
  resources :records
  post 'doctor/:id/records/new', to: 'records#create', as: 'new_doctor_record'
  get 'doctor/:id/records/new', to: 'records#new'
  get 'doctor/:id/records/index', to: 'records#index',
        as: 'doctor_records'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root 'main#home'
  get 'user/profile', as: 'user_root'
  get 'doctor/profile', as: 'doctor_root'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="mt-auto text-black-50 text-center">
  <p>Hospital app created by <%= link_to 'NikKi NailZz',  'https://gitlab.com/dethcrock'%>  </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">

  <div class="container-fluid">
    <%= link_to 'Hospital', root_path, {class: 'navbar-brand'}%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <span class="nav-link active">
            <%= link_to 'Главная', root_path %>
          </span>
        </li>
       <li class="nav-item">
          <span class="nav-link active">
            <%= link_to 'Список врачей', doctor_index_path %>
          </span>
        </li>
       <li class="nav-item">
         <% if user_signed_in? %>
          <span class="nav-link active">
            <%= link_to 'Профиль', user_root_path %>
          </span>

          <span class="nav-link active">
            <%= button_to 'Выход', destroy_user_session_path,
              {class: 'btn btn-primary', method: 'delete'}%>
          </span>
          <% elsif doctor_signed_in? %>
          <span class="nav-link active">
            <%= link_to 'Профиль', doctor_root_path %>
          </span>

          <span class="nav-link active">
            <%= button_to 'Выход', destroy_doctor_session_path,
              {class: 'btn btn-primary', method: 'delete'}%>
          </span>


          <% else %>
          <span class="nav-link active">
            <%= link_to 'Войти', user_session_path %>
          </span>
          <% end %>
        </li>
      </ul>
   </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js' %>
  </head>

<body>
  <div class="container">
      <div class="notice alert-success text-center"><%= notice %></div>
      <div class="alert-danger text-center"><%= alert %></div>
    <%= render 'layouts/header' %>
    <%= yield %>
<div class="pt-5"><%= render 'layouts/footer' %></div>  </div>
</body>
</html>